/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetjava;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.beans.PropertyVetoException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author asus
 */
public class Available extends javax.swing.JInternalFrame {
public String mess;
    /**
     * Creates new form Available
     */
    public Available(String msg) {
        initComponents();
        try{
            Connection cnx= DBConnect.openConnection();
            String s ="meuble";
            this.mess=msg;
            
            //System.out.print(donation);
            PreparedStatement ps=cnx.prepareStatement("SELECT ARTICLE_ID,NATURE,RECEIPT_QUANTITY,RECEIPT_DATE,DONATOR_FNAME,DONATOR_LNAME    FROM javadatabase.articles join\n" +
                                                        "javadatabase.category on \n" +
                                                        "javadatabase.articles.CATEGORY_ID = javadatabase.category.CATEGORY_ID join \n" +
                                                        "javadatabase.deposit_sale on\n" +
                                                        "javadatabase.deposit_sale.DEPSALE_ID=javadatabase.articles.DEPSALE_ID join\n" +
                                                        "javadatabase.type on \n" +
                                                        "javadatabase.type.TYPE_ID = javadatabase.articles.TYPE_ID join \n" +
                                                        "javadatabase.donators on \n" +
                                                        "javadatabase.donators.DONATOR_ID = javadatabase.articles.DONATOR_ID\n" +
                                                        "WHERE ( ARTICLE_STATUS = 'Accepted')\n" +
                                                        "and(RECEIVER_ID IS NULL)\n" +
                                                        "AND(javadatabase.category.CATEGORY_NAME=\""+mess+"\") and not(DEPSALE_STATUS='Sold') ;");
            ResultSet rs=ps.executeQuery();
            DefaultTableModel tm=(DefaultTableModel)jTable1.getModel();
            
            tm.setRowCount(0);
            
            while(rs.next()){
                Object o[] = {rs.getInt("ARTICLE_ID"), rs.getString("NATURE"),rs.getString("RECEIPT_QUANTITY"),rs.getString("RECEIPT_DATE"),rs.getString("DONATOR_FNAME"),rs.getString("DONATOR_LNAME")};
                tm.addRow(o);
            }
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(this, e);
        }
    }

  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setClosable(true);
        setPreferredSize(new java.awt.Dimension(700, 250));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ARTICLE_ID", "NATURE", "QUANTITY", "RECEIPT_DATE", "REC,DONATOR_FNAME", "DONATOR_LNAME"
            }
        ));
        jTable1.setPreferredSize(new java.awt.Dimension(600, 64));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 12, 604, 226));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
