/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package projetjava;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class Deposit_Update extends javax.swing.JFrame {
    Connection con= DBConnect.openConnection();
    PreparedStatement ps2=null;
    PreparedStatement ps3=null;
    PreparedStatement ps4=null;
    ResultSet rs2=null;
    ResultSet rs3=null;
    ResultSet rs4=null;
    int ID=0;
    int up=0;

    /** Creates new form Deposit_Update */
    public Deposit_Update() {
        this.setTitle("Deposit");
        initComponents();
        setResizable(false);
        setLocation(350,100);
        
        jLabel1.setVisible(false);
        jText_Nature.setVisible(false);
    }
    
    public Deposit_Update(int id,String nature, String Status, String Estimate, String Sale, String Sale_Date, String Deposit_Date){
        initComponents();
        this.addWindowListener(new java.awt.event.WindowAdapter() {
        @Override
        public void windowClosing(java.awt.event.WindowEvent windowEvent) {
             Deposit m = new Deposit(); // open the deposit menu 
             m.setVisible(true);
            try{
                con.close();
                dispose();
        }catch(Exception ex){System.out.println(ex.getMessage());}
        }
        });
        this.setTitle("Deposit Update");
        setResizable(false);
        setLocation(350,100);
        up=1;
        ID=id;
        jText_Nature.setText(nature);
        jText_Status.setText(Status);
        
        jText_Est.setText(Estimate);
       
        jText_Amount.setText(Sale);
        
        jText_SDate.setText(Sale_Date);
       
        jText_DDate.setText(Deposit_Date);
        
        jLabel_art.setVisible(false);
        jTextField_art.setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jText_Status = new javax.swing.JTextField();
        jText_Nature = new javax.swing.JTextField();
        jText_Amount = new javax.swing.JTextField();
        jText_Est = new javax.swing.JTextField();
        jText_SDate = new javax.swing.JTextField();
        jText_DDate = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel_art = new javax.swing.JLabel();
        jTextField_art = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(640, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nature");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, -1, -1));

        jLabel2.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Estimated Price");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, -1, -1));

        jLabel3.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Sale Amount");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, -1, -1));

        jLabel4.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Status");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, -1, -1));

        jLabel5.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Sale Date");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, -1, -1));

        jLabel6.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Deposit Date");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 440, -1, -1));

        jText_Status.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jText_StatusKeyPressed(evt);
            }
        });
        getContentPane().add(jText_Status, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 158, -1));

        jText_Nature.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jText_NatureKeyPressed(evt);
            }
        });
        getContentPane().add(jText_Nature, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 158, -1));
        getContentPane().add(jText_Amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, 158, -1));
        getContentPane().add(jText_Est, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 158, -1));
        getContentPane().add(jText_SDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 380, 158, -1));
        getContentPane().add(jText_DDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 460, 158, -1));

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 490, 51, -1));

        jLabel_art.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel_art.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_art.setText("Article ID");
        getContentPane().add(jLabel_art, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, -1, -1));
        getContentPane().add(jTextField_art, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 160, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetjava/greenhands.jpg"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -80, 700, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (up==1){
            String dep = "UPDATE deposit_sale SET depsale_status =? , estimate_price=?, sale_amount=?, sale_date=?, deposit_date=? WHERE depsale_id=?";
            try {  
                ps2 = con.prepareStatement(dep); 
                ps2.setString(1, jText_Status.getText());
                ps2.setString(2, jText_Est.getText());
                ps2.setString(3, jText_Amount.getText());
                ps2.setString(4, jText_SDate.getText());
                ps2.setString(5, jText_DDate.getText());
                ps2.setInt(6, ID);
                ps2.executeUpdate();
                JOptionPane.showMessageDialog(null, "Successfully updated...");
                dispose();
               // new Deposit().setVisible(true);
            } catch(SQLException ex){
                JOptionPane.showMessageDialog(null, ex);
            }
        }
        else{
            try {  
                String id="SELECT MAX(depsale_id) FROM deposit_sale";
                String dep="insert into deposit_sale(depsale_id, estimate_price, sale_amount, sale_date, depsale_status, deposit_date) values(?, ?, ?, ?, ?, ?)";
                String art="UPDATE articles SET article_status=?, depsale_id=? WHERE article_id=?";
                
                ps3 = con.prepareStatement(id);
                rs3=ps3.executeQuery();
                rs3.next();
                
                ps2 = con.prepareStatement(dep); 
                ps2.setInt(1, rs3.getInt(1)+1);
                ps2.setString(2, jText_Est.getText());
                ps2.setString(3, jText_Amount.getText());
                ps2.setString(4, jText_SDate.getText());
                ps2.setString(5, jText_Status.getText());
                ps2.setString(6, jText_DDate.getText());
                ps2.executeUpdate();
                
                ps4 = con.prepareStatement(art);
                ps4.setString(1, "Deposit");
                ps4.setInt(2, rs3.getInt(1)+1);
                ps4.setString(3, jTextField_art.getText());
                ps4.executeUpdate();
                
                JOptionPane.showMessageDialog(null, "Successfully added...");
                dispose();
                new Deposit().setVisible(true);
            } catch(SQLException ex){
                JOptionPane.showMessageDialog(null, ex);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jText_NatureKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jText_NatureKeyPressed
        char c=evt.getKeyChar();
        if(Character.isLetter(c)||Character.isWhitespace(c)||Character.isISOControl(c)){
            jText_Nature.setEditable(true);
        }else{
        jText_Nature.setEditable(false);
        }
    }//GEN-LAST:event_jText_NatureKeyPressed

    private void jText_StatusKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jText_StatusKeyPressed
        char c=evt.getKeyChar();
        if(Character.isLetter(c)||Character.isWhitespace(c)||Character.isISOControl(c)){
            jText_Status.setEditable(true);
        }else{
        jText_Status.setEditable(false);
        }
    }//GEN-LAST:event_jText_StatusKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Deposit_Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Deposit_Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Deposit_Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Deposit_Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Deposit_Update().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel_art;
    private javax.swing.JTextField jTextField_art;
    private javax.swing.JTextField jText_Amount;
    private javax.swing.JTextField jText_DDate;
    private javax.swing.JTextField jText_Est;
    private javax.swing.JTextField jText_Nature;
    private javax.swing.JTextField jText_SDate;
    private javax.swing.JTextField jText_Status;
    // End of variables declaration//GEN-END:variables

}
