/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetjava;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.beans.PropertyVetoException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author asus
 */
public class Donated extends javax.swing.JInternalFrame {
public String mess;
    /**
     * Creates new form Donated
     */
    public Donated(String msg) {
        initComponents();
        
        try{
            Connection cnx= DBConnect.openConnection();
            String s ="meuble";
            this.mess=msg;
            
            //System.out.print(donation);
            PreparedStatement ps=cnx.prepareStatement("SELECT ARTICLE_ID,NATURE,RECEIPT_QUANTITY,DONATION_DATE,RECEIVER_FNAME,RECEIVER_LNAME FROM javadatabase.articles join\n" +
                                                        "javadatabase.category on \n" +
                                                        "javadatabase.articles.CATEGORY_ID = javadatabase.category.CATEGORY_ID join\n" +
                                                        "javadatabase.type on \n" +
                                                        "javadatabase.type.TYPE_ID = javadatabase.articles.TYPE_ID join \n" +
                                                        "javadatabase.receivers on \n" +
                                                        "javadatabase.receivers.RECEIVER_ID = javadatabase.articles.RECEIVER_ID\n" +
                                                        "WHERE ( ARTICLE_STATUS = 'Accepted') AND (javadatabase.category.CATEGORY_NAME=\""+mess+"\");");
            ResultSet rs=ps.executeQuery();
            DefaultTableModel tm=(DefaultTableModel)jTable1.getModel();
            
            tm.setRowCount(0);
            
            while(rs.next()){
                Object o[] = {rs.getInt("ARTICLE_ID"), rs.getString("NATURE"),rs.getString("RECEIPT_QUANTITY"),rs.getString("DONATION_DATE"),rs.getString("RECEIVER_FNAME"),rs.getString("RECEIVER_LNAME")};
                tm.addRow(o);
            }
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(this, e);
        }
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setClosable(true);
        setPreferredSize(new java.awt.Dimension(700, 250));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ARTICLE_ID", "NATURE", "QUANTITY", "DONATION_DATE", "RECEIVER_FNAME", "RECEIVER_LNAME"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, true, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setPreferredSize(new java.awt.Dimension(600, 64));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
