package projetjava;
/**
 *
 * @author Maher Dissem
 */
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Members extends javax.swing.JFrame {

    /*String url="jdbc:mysql://localhost/javadatabase?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC";    
    String DB_user="root";
    String password="root";*/
    
    DefaultTableModel d=new DefaultTableModel();
    Connection con;
    Statement st;
    ResultSet res;
    public Members()
    {
        this.addWindowListener(new java.awt.event.WindowAdapter() {
        @Override
        public void windowClosing(java.awt.event.WindowEvent windowEvent) {
             MenuJFrame m = new MenuJFrame(); // open the main menu 
             m.setVisible(true);
            try{
                con.close();
                dispose();
        }catch(Exception ex){System.out.println(ex.getMessage());}
        }
        });
        
        
        initComponents();
        this.setLocation(400, 150);
        this.show();
     
        this.setTitle("Members");
        d=(DefaultTableModel) jTable1.getModel();
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(30);
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(200);
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(200);
        jTable1.getColumnModel().getColumn(3).setPreferredWidth(200);
        jTable1.getColumnModel().getColumn(4).setPreferredWidth(300);
        jTable1.getColumnModel().getColumn(5).setPreferredWidth(300);
        this.addWindowListener(new java.awt.event.WindowAdapter() {
        @Override
        public void windowClosing(java.awt.event.WindowEvent windowEvent) {
            // Menu m=new Menu(); // open the main menu 
            try{
                con.close();
                dispose();
        }catch(Exception ex){System.out.println(ex.getMessage());}
        }
        });
        try{
            Connection con= DBConnect.openConnection();
            /*Class.forName("com.mysql.cj.jdbc.Driver").newInstance();
            con = DriverManager.getConnection(url,DB_user,password);*/
            st=con.createStatement();
        }catch(Exception ex){System.out.println(ex.getMessage());}
        
        try
        {
            ResultSet rs=st.executeQuery("SELECT * FROM javadatabase.members;");
            while(rs.next())
            {
                String[] t=new String[]{
                    rs.getString("MEMBER_ID"),rs.getString("MEMBER_FNAME"),rs.getString("MEMBER_LNAME"),rs.getString("MEMBER_NUM"),rs.getString("MEMBER_ADR"),rs.getString("MEMBER_EMAIL")
                };     
                d.addRow(t);
            }           
        } catch (Exception ex) {
            JOptionPane jp=new JOptionPane("");
            jp.showMessageDialog(null, ex.toString(), "my title", JOptionPane.INFORMATION_MESSAGE);
        } 
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jTextField7 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetjava/greenhands.jpg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(540, 370));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Members");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 11, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "First name", "Last name", "Number", "Adress", "E-mail"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 79, 509, 192));

        jTextField2.setText("First name");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField2KeyPressed(evt);
            }
        });
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 287, 76, -1));

        jTextField3.setText("Last name");
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField3KeyPressed(evt);
            }
        });
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 287, 76, -1));

        jTextField4.setText("Number");
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 287, 79, -1));

        jTextField5.setText("Adress");
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 287, 76, -1));

        jTextField6.setText("Email");
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 287, 70, -1));

        jButton1.setText("Add Member");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(413, 283, -1, -1));

        jTextField7.setText("search term");
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 45, -1, -1));

        jButton2.setText("Search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 41, -1, -1));

        jButton3.setText("Remove");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(439, 41, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetjava/greenhands.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed
    public static boolean isNumeric(String strNum) {
        if (strNum == null) {
            return false;
        }
        try {
            double d = Double.parseDouble(strNum);
        } catch (NumberFormatException nfe) {
            return false;
        }
        return true;
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Add member
        try
        {
            int id=0,num;
            String fname,lname,adress,email;
            String req_id="SELECT max(MEMBER_ID) FROM javadatabase.members;";
            ResultSet rs_id=st.executeQuery(req_id);
            String max;
            while(rs_id.next())
            {
                max=rs_id.getString("max(MEMBER_ID)");
                if(max==null) id=0; // case of an empty database
                else
                id=Integer.valueOf(max);
            }
            id++;
            fname=jTextField2.getText();
            lname=jTextField3.getText();
            adress=jTextField5.getText();
            email=jTextField6.getText();
            if(!isNumeric(jTextField4.getText())){
                JOptionPane jp=new JOptionPane();
                jp.showMessageDialog(null, "Number input is not numerical", "Failure", JOptionPane.INFORMATION_MESSAGE);
                return;
                } 
            if(jTextField4.getText().equals("Number") || fname.equals("First name") || lname.equals("Last name") || adress.equals("Adress") || email.equals("Email")){
                JOptionPane jp=new JOptionPane();
                jp.showMessageDialog(null, "Please fill all the fields", "Failure", JOptionPane.INFORMATION_MESSAGE);
                return ;
            }
            num=Integer.parseInt(jTextField4.getText());
            String req="INSERT INTO `javadatabase`.`members` (`MEMBER_ID`, `MEMBER_FNAME`, `MEMBER_LNAME`, `MEMBER_NUM`, `MEMBER_ADR`, `MEMBER_EMAIL`) VALUES ("+id+",'"+fname+"','"+lname+"',"+num+",'"+adress+"','"+email+"');"; 
            int ins=st.executeUpdate(req);
            if(ins==1){ 
                JOptionPane jp=new JOptionPane();
                jp.showMessageDialog(null, "Member has been added to the database", "Success", JOptionPane.INFORMATION_MESSAGE);
                jTextField2.setText("First name");
                jTextField3.setText("Last name");
                jTextField4.setText("Number");
                jTextField5.setText("Adress");
                jTextField6.setText("Email");
            }
            ResultSet rs=st.executeQuery("SELECT * FROM javadatabase.members;");
            d.setRowCount(0); // clear jtable
            while(rs.next())
            {
                String[] t=new String[]{
                rs.getString("MEMBER_ID"),rs.getString("MEMBER_FNAME"),rs.getString("MEMBER_LNAME"),rs.getString("MEMBER_NUM"),rs.getString("MEMBER_ADR"),rs.getString("MEMBER_EMAIL")
                };
                d.addRow(t);
            }           
        } catch (Exception ex) {
            JOptionPane jp=new JOptionPane();
            jp.showMessageDialog(null, ex.toString(), "Failure", JOptionPane.INFORMATION_MESSAGE);
        } 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Search
        try
        {
            String search;
            search=jTextField7.getText();
            String req="SELECT * FROM javadatabase.members where MEMBER_ID like '%"+search+"%' or MEMBER_FNAME like '%"+search+"%' or MEMBER_LNAME like'%"+search+"%' or MEMBER_NUM like '%"+search+"%' or MEMBER_ADR like '%"+search+"%' or MEMBER_EMAIL like '%"+search+"%';";    
            if(search=="") req="SELECT * FROM javadatabase.members;";
            ResultSet rs=st.executeQuery(req);
            d.setRowCount(0); // clear jtable
            while(rs.next())
            {
                String[] t=new String[]{
                    rs.getString("MEMBER_ID"),rs.getString("MEMBER_FNAME"),rs.getString("MEMBER_LNAME"),rs.getString("MEMBER_NUM"),rs.getString("MEMBER_ADR"),rs.getString("MEMBER_EMAIL")
                };
                d.addRow(t);
            }           
        } catch (Exception ex) {
            JOptionPane jp=new JOptionPane();
            jp.showMessageDialog(null, ex.toString(), "Failure", JOptionPane.INFORMATION_MESSAGE);
        } 
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // Remove member
        try
        {
            int selectedRowIndex = jTable1.getSelectedRow();
            if(selectedRowIndex==-1)
            {
                JOptionPane jp=new JOptionPane();
                jp.showMessageDialog(null, "select a row first", "Failure", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            String id=(String) d.getValueAt(selectedRowIndex, 0);
            String req="DELETE FROM `javadatabase`.`members` WHERE MEMBER_ID="+id+";";
            int ins=st.executeUpdate(req);
            if(ins==1){ 
                JOptionPane jp=new JOptionPane();
                jp.showMessageDialog(null, "Member has been removed from the database", "Success", JOptionPane.INFORMATION_MESSAGE);
            }
            ResultSet rs=st.executeQuery("SELECT * FROM javadatabase.members;");
            d.setRowCount(0);
            while(rs.next())
            {
                String[] t=new String[]{
                    rs.getString("MEMBER_ID"),rs.getString("MEMBER_FNAME"),rs.getString("MEMBER_LNAME"),rs.getString("MEMBER_NUM"),rs.getString("MEMBER_ADR"),rs.getString("MEMBER_EMAIL")
                };             
                d.addRow(t);
            }           
        } catch (Exception ex) {
            JOptionPane jp=new JOptionPane();
            jp.showMessageDialog(null, ex.toString(), "Failure", JOptionPane.INFORMATION_MESSAGE);
        }  
    }//GEN-LAST:event_jButton3ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void jTextField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyPressed
        // do not accept numerical input
        char c=evt.getKeyChar();
        if(Character.isLetter(c)||Character.isWhitespace(c)||Character.isISOControl(c)){
            jTextField2.setEditable(true);
        }else{
        jTextField2.setEditable(false);
        }
    }//GEN-LAST:event_jTextField2KeyPressed

    private void jTextField3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyPressed
        // do not accept numerical input
        char c=evt.getKeyChar();
        if(Character.isLetter(c)||Character.isWhitespace(c)||Character.isISOControl(c)){
            jTextField3.setEditable(true);
        }else{
        jTextField3.setEditable(false);
        }
    }//GEN-LAST:event_jTextField3KeyPressed


    public static void main(String args[])
    {   
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Members().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
}
