/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetjava;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import projetjava.DBConnect;
import javax.swing.JOptionPane;

/**
 *
 * @author asus
 */
public class Ratio extends javax.swing.JFrame {
    Connection con;

    /**
     * Creates new form Ratio
     */
    public Ratio() {
         this.setTitle("Ratio");
         this.setLocation(400, 150);
        this.addWindowListener(new java.awt.event.WindowAdapter() {
        @Override
        public void windowClosing(java.awt.event.WindowEvent windowEvent) {
             Statistic m = new Statistic(); // open the main menu 
             m.setVisible(true);
            try{
                con.close();
                dispose();
                
        }catch(Exception ex){System.out.println(ex.getMessage());}
        }
        });
        initComponents();
        String jTextFieldstr1="";
        String jTextFieldstr2="";
        String jTextFieldstr3="";
        int r,a,b;
        
        
        try{
            
            Connection cnx= DBConnect.openConnection();
            PreparedStatement ps=cnx.prepareStatement("SELECT count(*)as article_nbr FROM javadatabase.articles;");
            ResultSet rs=ps.executeQuery();
            
            
            while(rs.next()){
                //System.out.print(rs.getString("donators_nbr"));
                jTextFieldstr1=rs.getString("article_nbr");
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
        
        
        
        try{
            
            Connection cnx= DBConnect.openConnection();
            PreparedStatement ps=cnx.prepareStatement("SELECT count(*) as artic_nbr_acc  FROM javadatabase.articles\n" +
                                                        "WHERE articles.ARTICLE_STATUS = \"Accepted\" ;");
            ResultSet rs=ps.executeQuery();
            
            
            while(rs.next()){
                //System.out.print(rs.getString("donators_nbr"));
                jTextFieldstr2=rs.getString("artic_nbr_acc");
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
            
        }
        try{
            
            Connection cnx= DBConnect.openConnection();
            PreparedStatement ps=cnx.prepareStatement("SELECT count(*) as artic_nbr_ruf FROM javadatabase.articles\n" +
                                                          "WHERE articles.ARTICLE_STATUS = \"Refused\" ;");
            ResultSet rs=ps.executeQuery();
            
            
            while(rs.next()){
                //System.out.print(rs.getString("donators_nbr"));
                jTextFieldstr3=rs.getString("artic_nbr_ruf");
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, e);   
        }
        
        r = Integer.parseInt(jTextFieldstr1);
        a = Integer.parseInt(jTextFieldstr2);
        b = Integer.parseInt(jTextFieldstr3);
        String s1=Float.toString((float)a/r*100);
        String s2=Float.toString((float)b/r*100);
        jTextField1.setText(s1+'%');
        jTextField2.setText(s2+'%');
       



    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        canvas1 = new java.awt.Canvas();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("  Ratio");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 84, 21));
        getContentPane().add(canvas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(386, 209, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Accepted donations: ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 160, 40));

        jTextField1.setText("jTextField1");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 110, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Refused donations:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 160, 30));

        jTextField2.setText("jTextField2");
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 110, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetjava/donation request.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ratio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ratio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ratio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ratio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ratio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Canvas canvas1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
