/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetjava;


import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import projetjava.DBConnect;

/**
 *
 * @author ASUS
 */
public class RequestInfo extends javax.swing.JFrame {

    /**
     * Creates new form RequestInfo
     * @param x
     */
    
    public RequestInfo(int x) {
        initComponents();
        try{
            Connection cnx= DBConnect.openConnection();
            PreparedStatement ps=cnx.prepareStatement("SELECT r.REQUEST_ID,a.DESCRIPTION,ar.REQUEST_QUANTITY,ar.REQUEST_DATE,d.DONATOR_FNAME,d.DONATOR_LNAME\n" +
            "from javadatabase.requests  r join javadatabase.article_request ar on r.REQUEST_ID = ar.REQUEST_ID \n" +
            "join javadatabase.articles a on a.ARTICLE_ID= ar.ARTICLE_ID\n" +
            "join javadatabase.donators d on d.DONATOR_ID=a.DONATOR_ID where r.REQUEST_ID="+x+";");
            ResultSet rs=ps.executeQuery();
            DefaultTableModel tm=(DefaultTableModel)jTable1.getModel();
            
            tm.setRowCount(0);
            
            while(rs.next()){
                Object o[] = { rs.getString("DESCRIPTION"),rs.getInt("REQUEST_QUANTITY"),
                    rs.getDate("REQUEST_DATE"), rs.getString("DONATOR_FNAME"),rs.getString("DONATOR_LNAME")};
                tm.addRow(o);
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
        jButton1.addActionListener(new ActionListener(){

            @Override
            public void actionPerformed(ActionEvent e) {
                Connection con= DBConnect.openConnection();
                PreparedStatement ps1=null;   
                String account = "UPDATE `javadatabase`.`requests` SET `REQUEST_STATUS` = 'Accepted' WHERE (`REQUEST_ID` = '"+x+"')";
                try {
                    ps1= con.prepareStatement(account);
                    ps1.executeUpdate(); 
                    JOptionPane.showMessageDialog(null, "Request Accepted");
                    dispose();
                } catch(SQLException ex){
                JOptionPane.showMessageDialog(null, ex);
            }
            }
        });
        jButton2.addActionListener(new ActionListener(){

            @Override
            public void actionPerformed(ActionEvent e) {
                Connection con= DBConnect.openConnection();
                PreparedStatement ps1=null;   
                String account = "UPDATE `javadatabase`.`requests` SET `REQUEST_STATUS` = 'Refused' WHERE (`REQUEST_ID` = '"+x+"')";
                try {
                    ps1= con.prepareStatement(account);
                    ps1.executeUpdate(); 
                    JOptionPane.showMessageDialog(null, "Request Refused");
                    dispose();
                } catch(SQLException ex){
                JOptionPane.showMessageDialog(null, ex);
            }
            }
        });
        jButton3.addActionListener(new ActionListener(){

            @Override
            public void actionPerformed(ActionEvent e) {
                Connection con= DBConnect.openConnection();
                PreparedStatement ps1=null;   
                String account = "UPDATE `javadatabase`.`requests` SET `REQUEST_STATUS` = 'InProgress' WHERE (`REQUEST_ID` = '"+x+"')";
                try {
                    ps1= con.prepareStatement(account);
                    ps1.executeUpdate(); 
                    JOptionPane.showMessageDialog(null, "Request InProgress");
                    dispose();
                } catch(SQLException ex){
                JOptionPane.showMessageDialog(null, ex);
            }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        FormListener formListener = new FormListener();

        setTitle("Request Informations");
        setResizable(false);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Description", "Quantity", "Date", "Don. Name", "Don. Last Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton1.setBackground(new java.awt.Color(153, 153, 0));
        jButton1.setText("Accept");
        jButton1.addActionListener(formListener);

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setText("Refuse");
        jButton2.addActionListener(formListener);

        jButton3.setBackground(new java.awt.Color(102, 102, 255));
        jButton3.setText("In Progress");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addContainerGap(324, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }

    // Code for dispatching events from components to event handlers.

    private class FormListener implements java.awt.event.ActionListener {
        FormListener() {}
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            if (evt.getSource() == jButton1) {
                RequestInfo.this.jButton1ActionPerformed(evt);
            }
            else if (evt.getSource() == jButton2) {
                RequestInfo.this.jButton2ActionPerformed(evt);
            }
        }
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton1;
    public javax.swing.JButton jButton2;
    public javax.swing.JButton jButton3;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
